# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_main', '0002_auto_20170712_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, default=None, related_name='profile_followers', to='tm_main.Profile'),
        ),
    ]
