# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=512)),
                ('season', models.IntegerField(choices=[(0, 'Winter'), (1, 'Summer'), (2, 'Fall'), (3, 'Spring'), (4, 'Any')], default=4)),
                ('piece', models.IntegerField(choices=[(0, 'Top'), (1, 'Bottom'), (2, 'Footwear'), (3, 'Headgear'), (4, 'Jacket'), (5, 'Accessory'), (6, 'Other')], default=6)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Neutral')], default=6)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('brands', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('ship_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('shipping_image', models.URLField()),
                ('return_image', models.URLField()),
                ('description', models.CharField(default='', max_length=512)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trunk_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_trunk', to='tm_trunk.Trunk'),
        ),
        migrations.AddField(
            model_name='item',
            name='trunk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_trunk', to='tm_trunk.Trunk'),
        ),
    ]
