# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tm_pictures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tm_trunk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='trunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_trunk', to='tm_trunk.Trunk'),
        ),
        migrations.AddField(
            model_name='inlinetag',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_tag', to='tm_pictures.Picture'),
        ),
        migrations.AddField(
            model_name='inlinetag',
            name='tagged_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
