# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tm_main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tm_main.Profile')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MatchListEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('match_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list', to='tm_match.MatchList')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_list_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['match_list__user'],
            },
        ),
    ]
