# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchlist',
            options={'ordering': ['profile']},
        ),
        migrations.RenameField(
            model_name='matchlist',
            old_name='user',
            new_name='profile',
        ),
    ]
