# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_match', '0002_auto_20170712_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchlistevent',
            options={'ordering': ['match_list__profile__user']},
        ),
    ]
